### ISSUE TITLE
Cannot call method 'charAt' of undefined

### ISSUE THREAD

**Issue by wfendler** [FWeinb/metalsmith-watch#22] opened 2015-05-14 03:39 UTC
I'm getting this error that I can't quite figure out:

```bash
$ node index
[metalsmith-serve] serving /Users/me/Sites/my-site/ms/build at http://localhost:8080

path.js:336
    var isAbsolute = path.charAt(0) === '/',
                          ^
TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at /Users/me/Sites/my-site/ms/node_modules/metalsmith-watch/dist/index.js:255:61
    at Array.map (native)
    at metalsmithWatch (/Users/me/Sites/my-site/ms/node_modules/metalsmith-watch/dist/index.js:254:32)
    at next (/Users/me/Sites/my-site/ms/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
    at /Users/me/Sites/my-site/ms/node_modules/metalsmith-serve/lib/index.js:52:5
    at Object.next [as _onImmediate] (/Users/me/Sites/my-site/ms/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

My `index.js` file:
```js
var Metalsmith   = require('metalsmith'),
    templates    = require('metalsmith-templates'),
    collections  = require('metalsmith-collections'),
    permalinks   = require('metalsmith-permalinks'),
    sass         = require('metalsmith-sass'),
    serve        = require('metalsmith-serve'),
    watch        = require('metalsmith-watch'),
    autoprefixer = require('metalsmith-autoprefixer');


Metalsmith(__dirname)
  // Set Permalinks
  .use(permalinks({
    pattern: ':permalink',
    relative: false
  }))

  // Compile Templates
  .use(templates('swig'))

  // Compile Sass
  .use(sass({
    outputStyle: 'compressed',
    outputDir: 'assets/styles'
  }))

  // Run autoprefixer on compiled Scss
  .use(autoprefixer())

  // Set Destination
  .destination('./build')

  // Serve up the destination directory
  .use(serve())

  // Watch for changes
  .use(watch({
    paths: {
      "${source}/**/*": true, // every changed files will trigger a rebuild of themselves
      "templates/**/*": "**/*", // every templates changed will trigger a rebuild of all files
    }
  }))

  // Create built files and send back any errors
  .build(function(err, files) {
    if (err) { throw err; }
  });

```

I've used what is shown in the documentation here but can't seem to get this one to work.

**Comment by MoOx** [comment] 2015-05-14 04:42
Hum it seems we have a problem with `metalsmith._source`.
Can you try something near `/Users/me/Sites/my-site/ms/node_modules/metalsmith-watch/dist/index.js:255:61`?
Can you add the line above something like `console.log(pattern, metalsmith._source)` so I can have a better idea on what is going on ?

Thanks !

**Comment by wfendler** [comment] 2015-05-14 05:14
@MoOx thanks for the quick response.

Added that line and the result is: `${source}/**/* undefined`

I don't know if this helps, but here's the directory structure as well:
![screen shot 2015-05-14 at 12 06 32 am](https://cloud.githubusercontent.com/assets/511928/7626391/2615d23e-f9ce-11e4-8c21-13b326b3fc5e.png)

**Comment by MoOx** [comment] 2015-05-14 05:16
Ok I did not except undefined.
Can you try
to set a metalsmith source please ?

```
  // Set source
  .source('./src')

  // Set Destination
  .destination('./build')
```

If that fix the problem I will know how to patch this.

**Comment by wfendler** [comment] 2015-05-14 05:19
Getting a new error:
```bash
$ node index

module.js:340
    throw err;
          ^
Error: Cannot find module 'metalsmith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/me/Sites/my-site/ms/index.js:1:82)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by MoOx** [comment] 2015-05-14 05:20
Did you add the .source() call in your index.js ?

**Comment by wfendler** [comment] 2015-05-14 05:23
@MoOx apologies. I had been moving things around to try some fixes and the `node_modules` at one point got removed.

Looks like I'm getting the same error after setting `.source()` in the index.js file still:

```bash
$ node index
${source}/**/* undefined

path.js:336
    var isAbsolute = path.charAt(0) === '/',
                          ^
TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at /Users/me/Sites/my-site/ms/node_modules/metalsmith-watch/dist/index.js:256:61
    at Array.map (native)
    at metalsmithWatch (/Users/me/Sites/my-site/ms/node_modules/metalsmith-watch/dist/index.js:254:32)
    at Object.next [as _onImmediate] (/Users/me/Sites/my-site/ms/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by MoOx** [comment] 2015-05-14 05:25
Hum this is weird.

It's supposed to be set in the constructor anyway https://github.com/segmentio/metalsmith/blob/master/lib/index.js#L43

Can you disable some others plugins to be sure it's not a buggy side effect ?

**Comment by clemsos** [comment] 2015-06-15 06:53
+1 I got the same error here

**Comment by MoOx** [comment] 2015-06-15 06:58
Same question as before:

> Can you disable some others plugins to be sure it's not a buggy side effect ?

**Comment by clemsos** [comment] 2015-06-15 07:05
No, i keep getting the error with only.

```
Metalsmith(__dirname) 
.source('src')
.use(
        watch({
          paths: {
            "${source}/**/*": true,
            "templates/**/*": "**/*.md",
          },
          livereload: true,
        })
      )
    // .destination('./build')
    .build(function (err) {
        // console.log(this._metadata.collections);
        if (err) {
            throw err;
        } else {
            // console.log(this);
        }
    })
    .destination('./build')
    .build(function (err) {
        // console.log(this._metadata.collections);
        if (err) {
            throw err;
        } else {
            // console.log(this);
        }
    })
```

Another error if I add the handlebards plugin just before the ```watch``` function.

```
╭─clemsos@clemsos  ~/Dev/topogram/topogram.github.io ‹› ‹build*› 
╰─$ node index.js                                                                                                                                 8 ↵
[metalsmith-watch] ✓ Live reload server started on port: 35729

/home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:22
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/node_modules/async/lib/async.js:22:31
    at /home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/lib/index.js:46:25
    at Function.exports.handlebars.render (/home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:499:5)
    at /home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:146:25
    at /home/clemsos/Dev/topogram/topogram.github.io/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

Maybe there is a version problem as well . Those are the versions I am using

```
─clemsos@clemsos  ~/Dev/topogram/topogram.github.io ‹› ‹build*› 
╰─$ npm list                                                                                                                                      8 ↵
topogram-docs@ /home/clemsos/Dev/topogram/topogram.github.io
├─┬ bullhorn-handlebars-helpers@0.5.0
│ ├── moment@2.9.0
│ ├── pagedown@1.1.0
│ └── underscore@1.7.0
├─┬ handlebars@2.0.0
│ ├─┬ optimist@0.3.7
│ │ └── wordwrap@0.0.2
│ └─┬ uglify-js@2.3.6
│   ├── async@0.2.10
│   └─┬ source-map@0.1.43
│     └── amdefine@0.1.0
├── highlight.js@8.4.0
├─┬ metalsmith@0.2.3
│ ├── async@0.2.10
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ ├─┬ defaults@1.0.0
│ │ └── clone@0.1.19
│ ├─┬ front-matter@0.2.1
│ │ └── yaml-js@0.1.0
│ ├─┬ fs-extra@0.8.1
│ │ ├── jsonfile@1.1.1
│ │ ├── mkdirp@0.3.5
│ │ ├── ncp@0.4.2
│ │ └── rimraf@2.2.8
│ ├── is-utf8@0.2.0
│ ├── recursive-readdir@0.0.2
│ └── ware@0.2.1
├─┬ metalsmith-collections@0.6.0
│ ├── debug@0.7.4
│ ├── extend@1.2.1
│ ├─┬ minimatch@0.2.14
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├─┬ read-metadata@0.0.2
│ │ └── yaml-js@0.0.8
│ └── uniq@0.0.2
├─┬ metalsmith-markdown@0.2.1
│ ├── debug@0.7.4
│ └── marked@0.3.2
├─┬ metalsmith-permalinks@0.1.3
│ ├── debug@0.7.4
│ ├── slug-component@1.1.0
│ └── substitute@0.0.1 (git://github.com/segmentio/substitute#08d9033cf50f657421da0a133c8b1f21f43b3e70)
├─┬ metalsmith-sass@0.5.0
│ ├── async@0.9.0
│ └─┬ node-sass@1.2.3
│   ├─┬ chalk@0.5.1
│   │ ├── ansi-styles@1.1.0
│   │ ├── escape-string-regexp@1.0.2
│   │ ├─┬ has-ansi@0.1.0
│   │ │ └── ansi-regex@0.2.1
│   │ ├─┬ strip-ansi@0.3.0
│   │ │ └── ansi-regex@0.2.1
│   │ └── supports-color@0.2.0
│   ├─┬ cross-spawn@0.2.3
│   │ └── lru-cache@2.5.0
│   ├─┬ gaze@0.5.1
│   │ └─┬ globule@0.1.0
│   │   ├─┬ glob@3.1.21
│   │   │ ├── graceful-fs@1.2.3
│   │   │ └── inherits@1.0.0
│   │   ├── lodash@1.0.1
│   │   └─┬ minimatch@0.2.14
│   │     ├── lru-cache@2.5.0
│   │     └── sigmund@1.0.0
│   ├── get-stdin@3.0.2
│   ├─┬ meow@2.1.0
│   │ ├─┬ camelcase-keys@1.0.0
│   │ │ ├── camelcase@1.0.2
│   │ │ └── map-obj@1.0.0
│   │ ├─┬ indent-string@1.2.0
│   │ │ └─┬ repeating@1.1.1
│   │ │   └── is-finite@1.0.0
│   │ ├── minimist@1.1.0
│   │ └── object-assign@2.0.0
│   ├─┬ mkdirp@0.5.0
│   │ └── minimist@0.0.8
│   ├─┬ mocha@2.1.0
│   │ ├── commander@2.3.0
│   │ ├─┬ debug@2.0.0
│   │ │ └── ms@0.6.2
│   │ ├── diff@1.0.8
│   │ ├── escape-string-regexp@1.0.2
│   │ ├─┬ glob@3.2.3
│   │ │ ├── graceful-fs@2.0.3
│   │ │ ├── inherits@2.0.1
│   │ │ └─┬ minimatch@0.2.14
│   │ │   ├── lru-cache@2.5.0
│   │ │   └── sigmund@1.0.0
│   │ ├── growl@1.8.1
│   │ └─┬ jade@0.26.3
│   │   ├── commander@0.6.1
│   │   └── mkdirp@0.3.0
│   ├── nan@1.6.1
│   ├── object-assign@1.0.0
│   ├── replace-ext@0.0.1
│   ├─┬ request@2.51.0
│   │ ├── aws-sign2@0.5.0
│   │ ├─┬ bl@0.9.4
│   │ │ └─┬ readable-stream@1.0.33
│   │ │   ├── core-util-is@1.0.1
│   │ │   ├── inherits@2.0.1
│   │ │   ├── isarray@0.0.1
│   │ │   └── string_decoder@0.10.31
│   │ ├── caseless@0.8.0
│   │ ├─┬ combined-stream@0.0.7
│   │ │ └── delayed-stream@0.0.5
│   │ ├── forever-agent@0.5.2
│   │ ├─┬ form-data@0.2.0
│   │ │ └─┬ mime-types@2.0.7
│   │ │   └── mime-db@1.5.0
│   │ ├─┬ hawk@1.1.1
│   │ │ ├── boom@0.4.2
│   │ │ ├── cryptiles@0.2.2
│   │ │ ├── hoek@0.9.1
│   │ │ └── sntp@0.2.4
│   │ ├─┬ http-signature@0.10.1
│   │ │ ├── asn1@0.1.11
│   │ │ ├── assert-plus@0.1.5
│   │ │ └── ctype@0.5.3
│   │ ├── json-stringify-safe@5.0.0
│   │ ├── mime-types@1.0.2
│   │ ├── node-uuid@1.4.2
│   │ ├── oauth-sign@0.5.0
│   │ ├── qs@2.3.3
│   │ ├── stringstream@0.0.4
│   │ ├─┬ tough-cookie@0.12.1
│   │ │ └── punycode@1.3.2
│   │ └── tunnel-agent@0.4.0
│   └── shelljs@0.3.0
├─┬ metalsmith-serve@0.0.3
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ └─┬ node-static@0.7.6
│   ├── colors@1.1.0
│   ├── mime@1.3.4
│   └─┬ optimist@0.6.1
│     ├── minimist@0.0.10
│     └── wordwrap@0.0.3
├─┬ metalsmith-templates@0.1.0
│ ├── async@0.2.10
│ ├── consolidate@0.10.0
│ ├── debug@0.7.4
│ └── extend@1.2.1
└─┬ metalsmith-watch@1.0.1
  ├── async@0.9.2
  ├─┬ chalk@1.0.0
  │ ├── ansi-styles@2.0.1
  │ ├── escape-string-regexp@1.0.3
  │ ├─┬ has-ansi@1.0.3
  │ │ ├── ansi-regex@1.1.1
  │ │ └── get-stdin@4.0.1
  │ ├─┬ strip-ansi@2.0.1
  │ │ └── ansi-regex@1.1.1
  │ └── supports-color@1.3.1
  ├─┬ gaze@0.5.1
  │ └─┬ globule@0.1.0
  │   ├─┬ glob@3.1.21
  │   │ ├── graceful-fs@1.2.3
  │   │ └── inherits@1.0.0
  │   ├── lodash@1.0.2
  │   └─┬ minimatch@0.2.14
  │     ├── lru-cache@2.6.4
  │     └── sigmund@1.0.1
  ├── metalsmith-filenames@1.0.0
  ├─┬ multimatch@2.0.0
  │ ├── array-differ@1.0.0
  │ ├─┬ array-union@1.0.1
  │ │ └── array-uniq@1.0.2
  │ └─┬ minimatch@2.0.8
  │   └─┬ brace-expansion@1.1.0
  │     ├── balanced-match@0.2.0
  │     └── concat-map@0.0.1
  ├─┬ tiny-lr@0.1.6
  │ ├─┬ body-parser@1.8.4
  │ │ ├── bytes@1.0.0
  │ │ ├── depd@0.4.5
  │ │ ├── iconv-lite@0.4.4
  │ │ ├── media-typer@0.3.0
  │ │ ├─┬ on-finished@2.1.0
  │ │ │ └── ee-first@1.0.5
  │ │ ├── qs@2.2.4
  │ │ ├── raw-body@1.3.0
  │ │ └─┬ type-is@1.5.7
  │ │   └─┬ mime-types@2.0.14
  │ │     └── mime-db@1.12.0
  │ ├─┬ debug@2.0.0
  │ │ └── ms@0.6.2
  │ ├─┬ faye-websocket@0.7.3
  │ │ └─┬ websocket-driver@0.5.4
  │ │   └── websocket-extensions@0.1.1
  │ ├── livereload-js@2.2.2
  │ ├── parseurl@1.3.0
  │ └── qs@2.2.5
  └─┬ unyield@0.0.1
    └── co@3.1.0
```

**Comment by clemsos** [comment] 2015-06-15 07:09
Ok, it was a version problem... I was using 0.2.3 but updating to 1.7.0 fixed it.

**Comment by MoOx** [comment] 2015-06-15 07:10
Ok good to know. I guess same problem apply to @wfendler.
Closing since he did not respond.

**Closed by MoOx** 2015-06-15 07:10 UTC
Labels: bug
